service: ocr-envelope-processor

provider:
  name: aws
  runtime: python3.11
  architecture: arm64
  region: us-east-1   # ✅ updated to match your Lambda layer
  timeout: 30
  memorySize: 512
  stackName: ocr-envelope-processor-stack

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::ocr-envelopes
            - arn:aws:s3:::ocr-envelopes/*

  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  ocr:
    handler: ocr_lambda.ocr_lambda.lambda_handler
    architecture: arm64
    events:
      - http:
          path: ocr
          method: post
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:211302765842:layer:poppler-layer-arm64:1  # ✅ exact ARN you created

package:
  individually: true
  exclude:
    - __pycache__/**
    - "*.pyc"
    - node_modules/**
    - .venv/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    useDownloadCache: false
    useStaticCache: false
