trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AWS_Credentials

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    cd lambda-ocr-final
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd lambda-ocr-final
    npm install -g serverless@3
    serverless deploy
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Deploy Lambda with Serverless'
